### ISSUE TITLE
确定这个开源解析代码是正确的吗，例子正常运行根本解析出来的是乱码啊，大家试过没有！

### ISSUE THREAD

**Issue by fengshangren** [tagphi/czdb-search-c#2]
![微信截图_20241017195116](https://github.com/user-attachments/assets/75e0cf01-9141-42c0-9468-84428e1e0a5f)
这是项目里例子执行的，解析出来的字符串全是乱码

**Comment by craigliu** [comment]
在windows运行需要设置显示字符集，现在字符是用UTF-8输出在windows终端显示乱码，你可以先自己改改看
